### ISSUE TITLE
Cannot install version 0.1.1-0.0.1; dependencies don't seem to work

### ISSUE THREAD

**Issue by jrsmith3** [jrsmith3/refmanage#42]
Attempting to install version 0.1.1-0.0.1 in a [conda](http://conda.pydata.org) virtual environment throws a bunch of errors. I think there's a problem in the `setup.py` in terms of the dependencies required for this package.

Example
=======
Create a conda virtual environment and attempt to install version 0.1.1-0.0.1 from github.

```
$ cd test
$ conda create -p ./env anaconda
$ source activate ./env/
$ pip install git+git://github.com/jrsmith3/refmanage.git@0.1.1-0.0.1#egg=refmanage
Downloading/unpacking refmanage from git+git://github.com/jrsmith3/refmanage.git@0.1.1-0.0.1
  Cloning git://github.com/jrsmith3/refmanage.git (to 0.1.1-0.0.1) to /private/var/folders/qs/jhzvfv7x41v8p_6y91p044ww0000gn/T/pip_build_jrsmith3/refmanage
  Running setup.py (path:/private/var/folders/qs/jhzvfv7x41v8p_6y91p044ww0000gn/T/pip_build_jrsmith3/refmanage/setup.py) egg_info for package refmanage
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/qs/jhzvfv7x41v8p_6y91p044ww0000gn/T/pip_build_jrsmith3/refmanage/setup.py", line 3, in <module>
        import refmanage
      File "refmanage/__init__.py", line 11, in <module>
        from fs_utils import *
      File "refmanage/fs_utils.py", line 4, in <module>
        import pathlib2 as pathlib
    ImportError: No module named pathlib2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/qs/jhzvfv7x41v8p_6y91p044ww0000gn/T/pip_build_jrsmith3/refmanage/setup.py", line 3, in <module>

    import refmanage

  File "refmanage/__init__.py", line 11, in <module>

    from fs_utils import *

  File "refmanage/fs_utils.py", line 4, in <module>

    import pathlib2 as pathlib

ImportError: No module named pathlib2

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/var/folders/qs/jhzvfv7x41v8p_6y91p044ww0000gn/T/pip_build_jrsmith3/refmanage
Storing debug log for failure in /Users/jrsmith3/.pip/pip.log
```

**Comment by jrsmith3** [comment]
Diagnosis
=========
The problem occurs in `setup.py` on line 3 introduced at 640eb27d227747711da8a29785501b7b8465f4f4. The problem is that `setup.py` attempts to import `refmanage`. However, `refmanage` depends on `pybtex` and `pathlib2`, either of which may not be installed on the user's system. If they aren't installed, something like the above error occurs.

Apparently, importing the `refmanage` package in `setup.py` can cause a race condition and is considered bad ([source](http://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package/2073599#2073599)).


Solution
========
According to the above [suggestion on stackoverflow](http://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package/2073599#2073599), the way to handle the version information is to abstract it into a file, similar to what I've done. The difference with the SO solution is to use the `execfile` command to import the verion information into the `setup.py` namespace.

So the solution is to use the `execfile` construction in `setup.py`.


Misc
====
For what its worth, here's the contents of `pip.log` from the failed install:

```
------------------------------------------------------------
/Users/jrsmith3/Desktop/test/env/bin/pip run on Sat Mar  7 19:03:11 2015
Downloading/unpacking refmanageclear from git+git://github.com/jrsmith3/refmanage.git@0.1.1-0.0.1
  Cloning git://github.com/jrsmith3/refmanage.git (to 0.1.1-0.0.1) to /private/var/folders/qs/jhzvfv7x41v8p_6y91p044ww0000gn/T/pip_build_jrsmith3/refmanageclear
  Found command 'git' at '/usr/local/bin/git'
  Running command /usr/local/bin/git clone -q git://github.com/jrsmith3/refmanage.git /private/var/folders/qs/jhzvfv7x41v8p_6y91p044ww0000gn/T/pip_build_jrsmith3/refmanageclear
Cleaning up...
Operation cancelled by user
Exception information:
Traceback (most recent call last):
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/site-packages/pip/req.py", line 1360, in unpack_url
    unpack_vcs_link(link, loc, only_download)
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/site-packages/pip/download.py", line 344, in unpack_vcs_link
    vcs_backend.unpack(location)
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/site-packages/pip/vcs/__init__.py", line 240, in unpack
    self.obtain(location)
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/site-packages/pip/vcs/git.py", line 111, in obtain
    call_subprocess([self.cmd, 'clone', '-q', url, dest])
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/site-packages/pip/util.py", line 687, in call_subprocess
    returned_stdout, returned_stderr = proc.communicate()
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/subprocess.py", line 796, in communicate
    self.wait()
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/Users/jrsmith3/Desktop/test/env/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```
